apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  selector:
    app: search-deployment
  ports:
  - name: search-service
    protocol: TCP
    port: 8080
    targetPort: 8080