apiVersion: v1
kind: Service
metadata:
  name: goods-service
  labels:
    app: goods-service
spec:
  selector:
    app: goods-deployment
  ports:
  - name: goods-service
    protocol: TCP
    port: 8080
    targetPort: 8080