apiVersion: v1
kind: Service
metadata:
  name: purchase-service
  labels:
    app: purchase-service
spec:
  selector:
    app: purchase-deployment
  ports:
  - name: purchase-service
    protocol: TCP
    port: 8080
    targetPort: 8080